# Generated by Django 5.2.3 on 2025-08-19 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_alter_problemcategory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='title',
            field=models.CharField(choices=[('Hardware', [('Note rejects', 'Note rejects'), ('Hardware Error', 'Hardware Error'), ('Broken part', 'Broken part'), ('Note jams pathway', 'Note jams pathway'), ('Note jams Escrow', 'Note jams Escrow')]), ('Software Related', [('Out of Service', 'Out of Service'), ('Account validation failing', 'Account validation failing'), ('Application offline', 'Application offline'), ('Application Unresponsive', 'Application Unresponsive'), ('Application Update', 'Application Update'), ('Front screen unavailable', 'Front screen unavailable'), ('Failed Transactions on terminal', 'Failed Transactions on terminal'), ('Server Update', 'Server Update'), ('E journal not uploading', 'E journal not uploading'), ('Template Update', 'Template Update'), ('Firmware update', 'Firmware update')]), ('Cash Reconciliation', [('Excess cash', 'Excess cash'), ('Cash shortage', 'Cash shortage')]), ('Power and Network', [('System off', 'System off'), ('System Offline', 'System Offline'), ('Faulty UPS/No clean Power', 'Faulty UPS/No clean Power')]), ('De-/Installation /Maintenance', [('Relocation', 'Relocation'), ('Configuration', 'Configuration'), ('Quarterly PM', 'Quarterly PM'), ('Re-imaging of the terminal', 'Re-imaging of the terminal')]), ('Safe', [('Lock/Key jam', 'Lock/Key jam'), ('Door jam', 'Door jam')]), ('SLA Related', [('General Complaint', 'General Complaint')])], max_length=255, null=True),
        ),
    ]
