# Generated by Django 5.2.3 on 2025-08-19 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_alter_ticket_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='title',
            field=models.CharField(default='Unknown Issue', max_length=255),
        ),
    ]
