# Generated by Django 5.2.3 on 2025-08-19 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_alter_ticket_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemcategory',
            name='name',
            field=models.CharField(choices=[('Hardware Related', 'Hardware Related'), ('Software Related', 'Software Related'), ('Cash Reconciliation', 'Cash Reconciliation'), ('Power and Network', 'Power and Network'), ('De-/Installation /Maintenance', 'De-/Installation /Maintenance'), ('Safe', 'Safe'), ('SLA Related', 'SLA Related')], max_length=100),
        ),
    ]
