# Generated by Django 5.2.3 on 2025-08-19 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_alter_ticket_problem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='problem_category',
            field=models.CharField(blank=True, choices=[('Hardware Related', 'Hardware Related'), ('Software Related', 'Software Related'), ('Cash Reconciliation', 'Cash Reconciliation'), ('Power and Network', 'Power and Network'), ('De-/Installation /Maintenance', 'De-/Installation /Maintenance'), ('Safe', 'Safe'), ('SLA Related', 'SLA Related')], max_length=100, null=True),
        ),
    ]
