# Generated by Django 5.2.3 on 2025-08-19 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_alter_ticket_problem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='problem_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.problemcategory'),
        ),
    ]
