# Generated by Django 5.2.3 on 2025-08-20 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_remove_ticket_title_alter_problemcategory_name_issue_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='issue',
            new_name='title',
        ),
    ]
