# Generated by Django 5.2.3 on 2025-08-20 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_rename_issue_ticket_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='title',
            new_name='issue',
        ),
    ]
