# Generated by Django 5.2.3 on 2025-08-20 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_rename_title_ticket_issue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='issue',
        ),
        migrations.AddField(
            model_name='ticket',
            name='title',
            field=models.CharField(default='Unknown Issue', max_length=255),
        ),
        migrations.AlterField(
            model_name='problemcategory',
            name='name',
            field=models.CharField(choices=[('Hardware Related', 'Hardware Related'), ('Software Related', 'Software Related'), ('Cash Reconciliation', 'Cash Reconciliation'), ('Power and Network', 'Power and Network'), ('De-/Installation /Maintenance', 'De-/Installation /Maintenance'), ('Safe', 'Safe'), ('SLA Related', 'SLA Related')], max_length=100),
        ),
        migrations.DeleteModel(
            name='Issue',
        ),
    ]
