# Generated by Django 5.2.3 on 2025-08-26 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_ticket_updated_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitylog',
            name='details',
        ),
    ]
